# Generated by Django 4.1.7 on 2023-03-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_total_number_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_number',
        ),
    ]
